"""initial schema

Revision ID: 22e63f2c5fbb
Revises: 
Create Date: 2026-03-04 18:07:06.780039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e63f2c5fbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('insured_name', sa.String(), nullable=False),
    sa.Column('insured_dob', sa.String(), nullable=True),
    sa.Column('policy_issue_date', sa.String(), nullable=True),
    sa.Column('face_amount', sa.Float(), nullable=True),
    sa.Column('beneficiary_name', sa.String(), nullable=True),
    sa.Column('beneficiary_email', sa.String(), nullable=True),
    sa.Column('beneficiary_phone', sa.String(), nullable=True),
    sa.Column('beneficiary_relationship', sa.String(), nullable=True),
    sa.Column('beneficiary_ssn_last4', sa.String(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('date_of_death', sa.String(), nullable=True),
    sa.Column('cause_of_death', sa.String(), nullable=True),
    sa.Column('manner_of_death', sa.String(), nullable=True),
    sa.Column('death_certificate_url', sa.String(), nullable=True),
    sa.Column('death_certificate_extracted', sa.JSON(), nullable=True),
    sa.Column('payout_method', sa.String(), nullable=True),
    sa.Column('bank_account_last4', sa.String(), nullable=True),
    sa.Column('routing_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'PENDING_DOCUMENTS', 'CONTESTABILITY_REVIEW', 'SIU_REVIEW', 'APPROVED', 'PAID', 'DENIED', name='claimstatus'), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('contestability_alert', sa.Boolean(), nullable=True),
    sa.Column('months_since_issue', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('assigned_adjuster', sa.String(), nullable=True),
    sa.Column('adjuster_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    # ### end Alembic commands ###
