"""add policy and adjuster models

Revision ID: 45203d40ecf0
Revises: 22e63f2c5fbb
Create Date: 2026-03-04 18:24:13.140210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45203d40ecf0'
down_revision: Union[str, Sequence[str], None] = '22e63f2c5fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_adjusters_username'), 'adjusters', ['username'], unique=True)
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_number', sa.String(), nullable=False),
    sa.Column('insured_name', sa.String(), nullable=False),
    sa.Column('insured_dob', sa.String(), nullable=True),
    sa.Column('insured_ssn_last4', sa.String(), nullable=True),
    sa.Column('face_amount', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=False),
    sa.Column('policy_type', sa.Enum('TERM', 'FINAL_EXPENSE', 'IUL', name='policytype'), nullable=False),
    sa.Column('status', sa.Enum('IN_FORCE', 'LAPSED', 'CANCELLED', name='policystatus'), nullable=True),
    sa.Column('beneficiaries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_adjusters_username'), table_name='adjusters')
    op.drop_table('adjusters')
    # ### end Alembic commands ###
