"""add jurisdiction_state to claims

Revision ID: 866d514cb121
Revises: 45203d40ecf0
Create Date: 2026-03-08 16:31:32.911984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866d514cb121'
down_revision: Union[str, Sequence[str], None] = '45203d40ecf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('jurisdiction_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'jurisdiction_state')
    # ### end Alembic commands ###
