"""add contestability analysis and document url fields

Revision ID: 8b8bd4d00e6d
Revises: 866d514cb121
Create Date: 2026-03-08 16:35:33.353554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8bd4d00e6d'
down_revision: Union[str, Sequence[str], None] = '866d514cb121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('contestability_analysis', sa.JSON(), nullable=True))
    op.add_column('policies', sa.Column('application_url', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('medical_records_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'medical_records_url')
    op.drop_column('policies', 'application_url')
    op.drop_column('claims', 'contestability_analysis')
    # ### end Alembic commands ###
